#!/bin/sh
# Set the wallpaper with feh base on the time of the day usin the images in the
# bitday collection: https://www.bitday.me
#
# It looks for the data files in $HOME/.config/bitday-wallpaper/SIZE where SIZE
# is passed as an env variable. Otherwise it tries to use 1920x1080.

if [ -z "$1" ]; then
  SIZE="1920x1080" # Default size
else
  SIZE="$1"
fi

WALL_DIR="$HOME/.config/bitday-wallpaper/${SIZE}/"

if [ ! -d "$WALL_DIR" ]; then
  echo "Not a directory: ${WALL_DIR}"
  exit 1
fi

HOUR=$(date +"%H")

if [ "$HOUR" -lt 3 ]; then
  IMAGE_PATH="${WALL_DIR}11-Mid-Night.png"
elif [ "$HOUR" -lt 6 ]; then 
  IMAGE_PATH="${WALL_DIR}12-Late-Night.png"
elif [ "$HOUR" -lt 7 ]; then
  IMAGE_PATH="${WALL_DIR}01-Early-Morning.png"
elif [ "$HOUR" -lt 8 ]; then
  IMAGE_PATH="${WALL_DIR}02-Mid-Morning.png"
elif [ "$HOUR" -lt 10 ]; then
  IMAGE_PATH="${WALL_DIR}03-Late-Morning.png"
elif [ "$HOUR" -lt 12 ]; then
  IMAGE_PATH="${WALL_DIR}04-Early-Afternoon.png"
elif [ "$HOUR" -lt 13 ]; then
  IMAGE_PATH="${WALL_DIR}05-Mid-Afternoon.png"
elif [ "$HOUR" -lt 16 ]; then
  IMAGE_PATH="${WALL_DIR}06-Late-Afternoon.png"
elif [ "$HOUR" -lt 19 ]; then
  IMAGE_PATH="${WALL_DIR}07-Early-Evening.png"
elif [ "$HOUR" -lt 20 ]; then
  IMAGE_PATH="${WALL_DIR}08-Mid-Evening.png"
elif [ "$HOUR" -lt 22 ]; then
  IMAGE_PATH="${WALL_DIR}09-Late-Evening.png"
elif [ "$HOUR" -lt 1 ]; then
  IMAGE_PATH="${WALL_DIR}10-Early-Night.png"
else
  IMAGE_PATH="${WALL_DIR}11-Mid-Night.png"
fi

if [ -S "$SWAYSOCK" ]; then
  # Sway environment
  swaymsg "exec swaybg --output DP-3 --image ${IMAGE_PATH}";
  swaymsg "exec swaybg -o HDMI-A-1 -i $HOME/Nextcloud/Photos/shared/Nordingrå\ 2020/D482B45C-6C16-4805-B4FE-C19212B5EDBC.jpeg"

  # Kill previous background
  sleep 0.2
  while [ "$(pgrep swaybg | wc -l)" -gt 2 ]; do
    pkill --oldest swaybg;
  done
elif [ -n "$DISPLAY" ]; then
  # XOrg environment
  feh --bg-fill --no-fehbg "$IMAGE_PATH"
fi
