# Don't print a new line at the start of the prompt
add_newline = false

[character]
success_symbol = "[ \\$](bold green)"
error_symbol = "[ \\$](bold red)"
vicmd_symbol = "[Vi](bold green)"

# Replace the "❯" symbol in the prompt with "➜"
# [character]                            # The name of the module we are configuring is "character"
# success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[aws]
disabled = true

[gcloud]
disabled = true

[cmd_duration]
show_notifications = true

[env_var.AWS_ENV_CUSTOM]
format = '[☁️  $env_value](bold yellow) '
